spring.datasource.url=jdbc:postgresql://localhost:5433/conluz_db
spring.datasource.username=luz
spring.datasource.password=blank

spring.influxdb.url=http://localhost:8087
spring.influxdb.username=luz
spring.influxdb.password=blank
spring.influxdb.database=conluz_db

conluz.security.jwt.secret-key=local-dev-only-not-a-secret-DO-NOT-USE-IN-PRODUCTION-0000000000
