# false flag indicates that authentication is disabled.
# This might be useful for local testing or in already-secure environments,
# but would not be recommended for production deployments.
auth_enabled: false

server:
  http_listen_port: 3100 # specifies that the Loki server will listen on port 3100.
common:
  # instance_addr and path_prefix define the address and path where the Loki instance will be running.
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage: # filesystem specifies that local file storage is being used for Loki.
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  # 1 and the ring section with kvstore: store: inmemory configure the Loki ring to use in-memory storage,
  # and a replication factor of 1. This is suitable for a single-node setup.
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
# Loki uses a concept called "schema config" to handle data on disk.
# Each schema configuration applies to data written after a particular date.
# In this case, the specified schema configuration applies to data written on or after 2025-04-12.
# It is important to note that the from field refers to the ingestion time in Loki not the timestamp of the log line itself.
schema_config:
  configs:
    - from: 2025-04-12
      store: tsdb # Defines the index type Loki will use. The options are boltdb-shipper, bigtable, cassandra, dynamodb, filesystem, and tsdb.
      object_store: filesystem # Specifies the object storage system to be used. Options are filesystem, gcs, s3, swift, and azure.
      schema: v13 # This is the version of the index schema to use.
      index:
        prefix: index_ # Prefix to be used for the index names.
        period: 24h # Determines how frequently a new set of index tables / files will be created. With a period of 24h, Loki creates a new set of index tables/files every day. This setting can help with data deletion and data re-indexing.
