package org.lucoenergia.conluz.infrastructure.shared;

public enum EnvVar {

    CONLUZ_JWT_SECRET_KEY,
    CONLUZ_USER_DEFAULT_ADMIN_ID,
    CONLUZ_USER_DEFAULT_ADMIN_PASSWORD,
    CONLUZ_USER_DEFAULT_ADMIN_NUMBER,
    CONLUZ_USER_DEFAULT_ADMIN_FULL_NAME,
    CONLUZ_USER_DEFAULT_ADMIN_ADDRESS,
    CONLUZ_USER_DEFAULT_ADMIN_EMAIL;
}
