server:
  http_listen_port: 3110 # Promtail will listen for HTTP requests on port 3110.
  grpc_listen_port: 0 # Disables gRPC (Google Remote Procedure Call) for this Promtail server

positions:
  filename: /tmp/positions.yaml # Specifies the file path where Promtail will store the current positions in the logs. This information is used to resume scraping after a restart.
clients:
  - url: http://loki:3100/loki/api/v1/push # Configures Promtail to push logs to Loki, a horizontally scalable, highly available log aggregation system.
scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Filter only by container "conluz"
      - source_labels: [ __meta_docker_container_name ]
        regex: "/conluz"
        action: keep

      # Assign a mandatory label: container_name
      - source_labels: [ __meta_docker_container_name ]
        regex: "/(.*)"
        target_label: container_name

      # Aggregate an extra label just in case
      - target_label: job
        replacement: docker-logs

      # Path to the logs
      - source_labels: [ __meta_docker_container_id ]
        target_label: __path__
        replacement: /var/lib/docker/containers/${1}/*.log